### ISSUE TITLE
v0.6.0 checklist

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary-def#69]
- [x] update `$.create` to take a record rather than positional arguments (#65)
  - [x] define Pair type constructor (#68)
  - [x] document `$.test` (#70)
  - [x] post upgrade guide (#72)
